// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFpRG_jytNUVZuMQ4sauh2aUhL7KoWgD4',
    appId: '1:628846219953:web:ed6793fe3bfa1e60e40890',
    messagingSenderId: '628846219953',
    projectId: 'prototype-e9de4',
    authDomain: 'prototype-e9de4.firebaseapp.com',
    storageBucket: 'prototype-e9de4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ_UsMwj0HHjmpxKP03kVII5kbMvsfv0c',
    appId: '1:628846219953:android:fe572a5e5efb19fae40890',
    messagingSenderId: '628846219953',
    projectId: 'prototype-e9de4',
    storageBucket: 'prototype-e9de4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFpRG_jytNUVZuMQ4sauh2aUhL7KoWgD4',
    appId: '1:628846219953:web:4da6a5b54e5ad275e40890',
    messagingSenderId: '628846219953',
    projectId: 'prototype-e9de4',
    authDomain: 'prototype-e9de4.firebaseapp.com',
    storageBucket: 'prototype-e9de4.firebasestorage.app',
  );
}
